name: Update Landing

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Update project in the server
    runs-on: ubuntu-latest

    steps:
      - name: Run remote script over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script:
            cd /var/www/LANDINGcarso || exit 1
            git pull origin main
            sudo systemctl restart nginx