name: Update Landing

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Update project in the server
    runs-on: ubuntu-latest

    steps:
      - name: Run remote script over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "Перехожу в директорию проекта"
            cd /var/www/LANDINGcarso || exit 1
            git remote set-url origin git@github.com:KAMAbee/LANDINGcarso.git
            echo "Установка доверия к github.com"
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git remote -v
            echo "Выполняю git pull..."
            git pull origin main
      
            echo "Git pull завершён. Последний commit:"
            git log -1
            echo "Перезапуск NGINX..."
            sudo systemctl restart nginx
            echo "Деплой завершён"
